In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,5,7,8])
arr1

array([1, 2, 5, 7, 8])

In [3]:
print(arr1)

[1 2 5 7 8]


In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
# built-in functions are indentified in round brackets
# class is member of function and member of method
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# to check the dimension in an array
print(arr.ndim)

1


In [7]:
# set has a property that It won't allow an mutable data in it's immutable
arr1 = np.array([[1,2,3,4], [4,3,5,3]])
print(arr1)
print(arr1.ndim)

[[1 2 3 4]
 [4 3 5 3]]
2


In [8]:
arr1 = np.array([[[1,2,3,4], [4,3,5,3], [7,8,9,5]]])

In [9]:
arr1
print(arr1.ndim)

3


In [10]:
arr3 = np.zeros([2,3])
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
arr4 = np.ones([2,3])
arr4

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arr5 = np.identity((4))
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
arr6 = np.arange(10,20,3)
arr6

array([10, 13, 16, 19])

In [14]:
arr7 = np.linspace(10,20,4)
arr7

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [15]:
arr8 = np.copy(arr4)

In [16]:
arr8

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
arr9 = np.array([[[1,3],[3,4]],[[5,6],[4,6]]])
print(arr9.ndim)

3


In [18]:
arr9

array([[[1, 3],
        [3, 4]],

       [[5, 6],
        [4, 6]]])

In [19]:
arr9.shape

(2, 2, 2)

In [20]:
arr10 = np.array([[[[1,2], [3,4]]]])
print(arr10)
print(arr10.ndim)

[[[[1 2]
   [3 4]]]]
4


In [21]:
# to check the no.  elements present in an array
arr10.size

4

In [22]:
arr10.shape

(1, 1, 2, 2)

In [23]:
arr10.itemsize

4

In [24]:
print(arr10)
print(arr10.dtype)

[[[[1 2]
   [3 4]]]]
int32


In [25]:
# to transform the datatype use arr.astype("data type to convert into")
arr10.astype("float")

array([[[[1., 2.],
         [3., 4.]]]])

In [26]:
import sys

In [27]:
lista = range(100)
arr1 = np.arange(100)

In [28]:
print(sys.getsizeof(34)*len(lista))

2800


In [29]:
print(arr1.itemsize*arr1.size)

400


## Indexing, Slicing and Iteration

In [30]:
# to reshape an array the condition should satisfy 
# if the array is of 24 elements then arr.reshape(x,y) x*y should be = 24
arr1 = np.arange(24)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [31]:
arr = arr1.reshape(6,4)

In [32]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [33]:
# Slicing 
arr[0][2:]

array([2, 3])

In [34]:
# to get an multpile items (arr[:(rows):, :(columns]
arr[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [35]:
arr[4:,:2]

array([[16, 17],
       [20, 21]])

In [36]:
arr[2:5,1:3]

array([[ 9, 10],
       [13, 14],
       [17, 18]])

In [37]:
arr2 = np.arange(30)
print(arr2, "\n")
print(arr2.reshape(5,6),"\n")
print(arr2.reshape(3,10), "\n")
print(arr2.reshape(15,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] 

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]]


In [42]:
arr2 = arr2.reshape(5,6)

In [43]:
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [46]:
arr2[2:4, 1:5]

array([[13, 14, 15, 16],
       [19, 20, 21, 22]])

In [49]:
arr2[0:4,1:5]

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22]])

In [59]:
# in indexing you can also determine step size arr2[:(rows) :(stepsize), :(columns):(stepsize)]
print(arr2[0:6,0:6:2])

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]
 [24 26 28]]


In [65]:
print(arr2[0::2,1::2])

[[ 1  3  5]
 [13 15 17]
 [25 27 29]]


In [68]:
arr2.size

30

In [69]:
arr2.itemsize

4

In [70]:
# to remember the loop
# for iterator in iterable
for i in arr2:
    print(i)
    

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]


In [71]:
# to apply filteron every pixel of image
for i in np.nditer(arr2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


# Numpy Operation

In [72]:
narr1 = np.array([1,2,3,4,5,6])
narr2 = np.array([4,5,6,7,8,9])
print(narr1)
print(narr2)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [78]:
# Addition
print(narr1 + narr2, "\n")
# Subtraction
print(narr1 - narr2, "\n")
# Multiplication
print(narr1 * narr2, "\n")
# Dividion
print(narr1 / narr2, "\n")


[ 5  7  9 11 13 15] 

[-3 -3 -3 -3 -3 -3] 

[ 4 10 18 28 40 54] 

[0.25       0.4        0.5        0.57142857 0.625      0.66666667] 



In [80]:
print(narr1**2)

[ 1  4  9 16 25 36]


In [82]:
narr1>3

array([False, False, False,  True,  True,  True])

In [83]:
narr3 = np.arange(6).reshape(2,3)
narr4 = np.arange(6).reshape(3,2)
print(narr3)
print(narr4)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [84]:
narr3 * narr4

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [86]:
# for multiplication in matrices m1xn1 = m2xn2 where as n1 = m2
arr5 = narr3.dot(narr4)

In [87]:
arr5

array([[10, 13],
       [28, 40]])

In [88]:
arr5.max()

40

In [89]:
arr5.min()

10

In [90]:
# to get the min value row wise
arr5.min(axis=0)

array([10, 13])

In [91]:
arr5.min(axis=1)

array([10, 28])

In [92]:
arr5.max(axis=1)

array([13, 40])

In [93]:
arr5.mean()

22.75

In [95]:
arr5.std()

12.07010770457331

In [96]:
arr5.var()

145.6875

## Reshaping Numpy Arrays

In [97]:
arr5.ndim

2

In [98]:
arr5

array([[10, 13],
       [28, 40]])

In [101]:
# to convert from higher dimension to one dimension
arr6 = arr5.ravel()

In [102]:
arr6

array([10, 13, 28, 40])

In [103]:
arr6.ndim

1

In [104]:
# Transpose
print(arr5.transpose())

[[10 28]
 [13 40]]


In [106]:
# To stack 
narr6 = np.arange(4).reshape(2,2)
print(narr6)

[[0 1]
 [2 3]]


In [107]:
np.hstack((arr5,narr6))

array([[10, 13,  0,  1],
       [28, 40,  2,  3]])

In [110]:
narr7 = np.arange(9).reshape(3,3)
narr8 = np.arange(9).reshape(3,3)
print(narr7)
print(narr8)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [112]:
np.hstack((narr7,narr8))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [113]:
np.vstack((narr7,narr8))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [115]:
# splitting hsplit and v split
np.hsplit(arr5,2)

[array([[10],
        [28]]),
 array([[13],
        [40]])]

In [117]:
np.vsplit(arr5,2)

[array([[10, 13]]), array([[28, 40]])]